---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Reset SSH connection to allow user changes to affect ansible user
  meta: reset_connection

- name: Install git
  apt:
    name: git
    state: present

- name: Clone simple-go repository
  git:
    repo: 'https://github.com/AB-Rhman/sqr-Task.git'
    dest: '/home/{{ ansible_user }}/sqr-Task'
    force: yes

- name: Install Docker Compose package
  apt:
    name: docker-compose-plugin
    state: present
    update_cache: yes

- name: Build and start Docker Compose services
  community.docker.docker_compose_v2:
    project_src: '/home/{{ ansible_user }}/sqr-Task/backend'
    files:
      - docker-compose.yml
    build: "always"
    pull: "missing"
    state: present
    recreate: always